// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: TDCmicroserviceAPI.proto

package learningpb

import (
	context "context"
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	"google.golang.org/grpc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindLearningTrailByDateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *FindLearningTrailByDateRequest) Reset() {
	*x = FindLearningTrailByDateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TDCmicroserviceAPI_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindLearningTrailByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLearningTrailByDateRequest) ProtoMessage() {}

func (x *FindLearningTrailByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TDCmicroserviceAPI_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLearningTrailByDateRequest.ProtoReflect.Descriptor instead.
func (*FindLearningTrailByDateRequest) Descriptor() ([]byte, []int) {
	return file_TDCmicroserviceAPI_proto_rawDescGZIP(), []int{0}
}

func (x *FindLearningTrailByDateRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type FindAllLearningTrailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindAllLearningTrailRequest) Reset() {
	*x = FindAllLearningTrailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TDCmicroserviceAPI_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllLearningTrailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllLearningTrailRequest) ProtoMessage() {}

func (x *FindAllLearningTrailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TDCmicroserviceAPI_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllLearningTrailRequest.ProtoReflect.Descriptor instead.
func (*FindAllLearningTrailRequest) Descriptor() ([]byte, []int) {
	return file_TDCmicroserviceAPI_proto_rawDescGZIP(), []int{1}
}

type LearningTrailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LearningTrails []*LearningTrail `protobuf:"bytes,1,rep,name=learning_trails,json=learningTrails,proto3" json:"learning_trails,omitempty"`
}

func (x *LearningTrailResponse) Reset() {
	*x = LearningTrailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TDCmicroserviceAPI_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LearningTrailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearningTrailResponse) ProtoMessage() {}

func (x *LearningTrailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TDCmicroserviceAPI_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearningTrailResponse.ProtoReflect.Descriptor instead.
func (*LearningTrailResponse) Descriptor() ([]byte, []int) {
	return file_TDCmicroserviceAPI_proto_rawDescGZIP(), []int{2}
}

func (x *LearningTrailResponse) GetLearningTrails() []*LearningTrail {
	if x != nil {
		return x.LearningTrails
	}
	return nil
}

type LearningTrail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lectures []*Lecture             `protobuf:"bytes,2,rep,name=lectures,proto3" json:"lectures,omitempty"`
	Date     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *LearningTrail) Reset() {
	*x = LearningTrail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TDCmicroserviceAPI_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LearningTrail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearningTrail) ProtoMessage() {}

func (x *LearningTrail) ProtoReflect() protoreflect.Message {
	mi := &file_TDCmicroserviceAPI_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearningTrail.ProtoReflect.Descriptor instead.
func (*LearningTrail) Descriptor() ([]byte, []int) {
	return file_TDCmicroserviceAPI_proto_rawDescGZIP(), []int{3}
}

func (x *LearningTrail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LearningTrail) GetLectures() []*Lecture {
	if x != nil {
		return x.Lectures
	}
	return nil
}

func (x *LearningTrail) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type Lecture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Speaker     *Speaker               `protobuf:"bytes,3,opt,name=speaker,proto3" json:"speaker,omitempty"`
	Time        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *Lecture) Reset() {
	*x = Lecture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TDCmicroserviceAPI_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lecture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lecture) ProtoMessage() {}

func (x *Lecture) ProtoReflect() protoreflect.Message {
	mi := &file_TDCmicroserviceAPI_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lecture.ProtoReflect.Descriptor instead.
func (*Lecture) Descriptor() ([]byte, []int) {
	return file_TDCmicroserviceAPI_proto_rawDescGZIP(), []int{4}
}

func (x *Lecture) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Lecture) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Lecture) GetSpeaker() *Speaker {
	if x != nil {
		return x.Speaker
	}
	return nil
}

func (x *Lecture) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type Speaker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SelfDescription string         `protobuf:"bytes,2,opt,name=self_description,json=selfDescription,proto3" json:"self_description,omitempty"`
	SocialMedias    []*SocialMedia `protobuf:"bytes,3,rep,name=social_medias,json=socialMedias,proto3" json:"social_medias,omitempty"`
}

func (x *Speaker) Reset() {
	*x = Speaker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TDCmicroserviceAPI_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Speaker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Speaker) ProtoMessage() {}

func (x *Speaker) ProtoReflect() protoreflect.Message {
	mi := &file_TDCmicroserviceAPI_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Speaker.ProtoReflect.Descriptor instead.
func (*Speaker) Descriptor() ([]byte, []int) {
	return file_TDCmicroserviceAPI_proto_rawDescGZIP(), []int{5}
}

func (x *Speaker) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Speaker) GetSelfDescription() string {
	if x != nil {
		return x.SelfDescription
	}
	return ""
}

func (x *Speaker) GetSocialMedias() []*SocialMedia {
	if x != nil {
		return x.SocialMedias
	}
	return nil
}

type SocialMedia struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Icon string `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	Link string `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *SocialMedia) Reset() {
	*x = SocialMedia{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TDCmicroserviceAPI_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocialMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialMedia) ProtoMessage() {}

func (x *SocialMedia) ProtoReflect() protoreflect.Message {
	mi := &file_TDCmicroserviceAPI_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialMedia.ProtoReflect.Descriptor instead.
func (*SocialMedia) Descriptor() ([]byte, []int) {
	return file_TDCmicroserviceAPI_proto_rawDescGZIP(), []int{6}
}

func (x *SocialMedia) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SocialMedia) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *SocialMedia) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

var File_TDCmicroserviceAPI_proto protoreflect.FileDescriptor

var file_TDCmicroserviceAPI_proto_rawDesc = []byte{
	0x0a, 0x18, 0x54, 0x44, 0x43, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x41, 0x50, 0x49, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x1e, 0x46, 0x69, 0x6e, 0x64, 0x4c, 0x65, 0x61,
	0x72, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x44, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x1d, 0x0a, 0x1b, 0x46, 0x69, 0x6e, 0x64, 0x41,
	0x6c, 0x6c, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x59, 0x0a, 0x15, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69,
	0x6e, 0x67, 0x54, 0x72, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x40, 0x0a, 0x0f, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x72, 0x61, 0x69,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x65, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x69,
	0x6c, 0x52, 0x0e, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x69, 0x6c,
	0x73, 0x22, 0x82, 0x01, 0x0a, 0x0d, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x72,
	0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x6c, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x08, 0x6c, 0x65,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x9c, 0x01, 0x0a, 0x07, 0x4c, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x07, 0x73, 0x70, 0x65, 0x61,
	0x6b, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x52, 0x07, 0x73, 0x70,
	0x65, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x07, 0x53, 0x70, 0x65, 0x61, 0x6b, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x65, 0x6c, 0x66, 0x5f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x73, 0x65, 0x6c, 0x66, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x3a, 0x0a, 0x0d, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69,
	0x6e, 0x67, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x0c,
	0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x73, 0x22, 0x49, 0x0a, 0x0b,
	0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69,
	0x63, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x32, 0xc1, 0x02, 0x0a, 0x10, 0x4c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x69, 0x6c, 0x41, 0x70, 0x69, 0x12, 0x60, 0x0a, 0x11,
	0x46, 0x69, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x69,
	0x6c, 0x12, 0x28, 0x2e, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x69, 0x6c, 0x42, 0x79,
	0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6c, 0x65,
	0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x54,
	0x72, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x60,
	0x0a, 0x14, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x54, 0x72, 0x61, 0x69, 0x6c, 0x12, 0x25, 0x2e, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x54, 0x72, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x54, 0x72, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x69, 0x0a, 0x1a, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4c, 0x65, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x12, 0x28,
	0x2e, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4c, 0x65,
	0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x44, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6c, 0x65, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1d, 0x5a, 0x1b, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2f,
	0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var _ context.Context
var _ grpc.ClientConnInterface

type LearningTrailAPIClient interface {
	FindLearningTrail(ctx context.Context, in *FindLearningTrailByDateRequest, opts ...grpc.CallOption) (*LearningTrailResponse, error)
}

type learningTrailAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewLearningTrailAPIClient(cc grpc.ClientConnInterface) LearningTrailAPIClient {
	return &learningTrailAPIClient(cc)
}

func (c *learningTrailAPIClient) FindLearningTrail(ctx context.Context, in *FindLearningTrailByDateRequest, opts ...grpc.CallOption) (*LearningTrailResponse, error) {
	out := new(LearningTrailResponse)
	err := c.cc.Invoke(ctx, "/TDCmicroserviceAPI.LearningTrailApi/FindLearningTrail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type LearningTrailAPIServer interface {
	FindLearningTrail(context.Context, *FindLearningTrailByDateRequest)
}

func RegisterLearningTrailAPIServer(s *grpc.Server, srv LearningTrailAPIServer) {
	s.RegisterService(&_GreetService_serviceDesc, srv)
}

var _GreetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TDCmicroserviceAPI.LearningTrailApi",
	HandlerType: (*LearningTrailAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _GreetService_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greetpb/greet.proto",
}

var (
	file_TDCmicroserviceAPI_proto_rawDescOnce sync.Once
	file_TDCmicroserviceAPI_proto_rawDescData = file_TDCmicroserviceAPI_proto_rawDesc
)

func file_TDCmicroserviceAPI_proto_rawDescGZIP() []byte {
	file_TDCmicroserviceAPI_proto_rawDescOnce.Do(func() {
		file_TDCmicroserviceAPI_proto_rawDescData = protoimpl.X.CompressGZIP(file_TDCmicroserviceAPI_proto_rawDescData)
	})
	return file_TDCmicroserviceAPI_proto_rawDescData
}

var file_TDCmicroserviceAPI_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_TDCmicroserviceAPI_proto_goTypes = []interface{}{
	(*FindLearningTrailByDateRequest)(nil), // 0: learning.FindLearningTrailByDateRequest
	(*FindAllLearningTrailRequest)(nil),    // 1: learning.FindAllLearningTrailRequest
	(*LearningTrailResponse)(nil),          // 2: learning.LearningTrailResponse
	(*LearningTrail)(nil),                  // 3: learning.LearningTrail
	(*Lecture)(nil),                        // 4: learning.Lecture
	(*Speaker)(nil),                        // 5: learning.Speaker
	(*SocialMedia)(nil),                    // 6: learning.SocialMedia
	(*timestamppb.Timestamp)(nil),          // 7: google.protobuf.Timestamp
}
var file_TDCmicroserviceAPI_proto_depIdxs = []int32{
	7,  // 0: learning.FindLearningTrailByDateRequest.date:type_name -> google.protobuf.Timestamp
	3,  // 1: learning.LearningTrailResponse.learning_trails:type_name -> learning.LearningTrail
	4,  // 2: learning.LearningTrail.lectures:type_name -> learning.Lecture
	7,  // 3: learning.LearningTrail.date:type_name -> google.protobuf.Timestamp
	5,  // 4: learning.Lecture.speaker:type_name -> learning.Speaker
	7,  // 5: learning.Lecture.time:type_name -> google.protobuf.Timestamp
	6,  // 6: learning.Speaker.social_medias:type_name -> learning.SocialMedia
	0,  // 7: learning.LearningTrailApi.FindLearningTrail:input_type -> learning.FindLearningTrailByDateRequest
	1,  // 8: learning.LearningTrailApi.FindAllLearningTrail:input_type -> learning.FindAllLearningTrailRequest
	0,  // 9: learning.LearningTrailApi.FindAllLearningTrailByDate:input_type -> learning.FindLearningTrailByDateRequest
	2,  // 10: learning.LearningTrailApi.FindLearningTrail:output_type -> learning.LearningTrailResponse
	2,  // 11: learning.LearningTrailApi.FindAllLearningTrail:output_type -> learning.LearningTrailResponse
	2,  // 12: learning.LearningTrailApi.FindAllLearningTrailByDate:output_type -> learning.LearningTrailResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_TDCmicroserviceAPI_proto_init() }
func file_TDCmicroserviceAPI_proto_init() {
	if File_TDCmicroserviceAPI_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TDCmicroserviceAPI_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindLearningTrailByDateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TDCmicroserviceAPI_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllLearningTrailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TDCmicroserviceAPI_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LearningTrailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TDCmicroserviceAPI_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LearningTrail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TDCmicroserviceAPI_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lecture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TDCmicroserviceAPI_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Speaker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TDCmicroserviceAPI_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocialMedia); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TDCmicroserviceAPI_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_TDCmicroserviceAPI_proto_goTypes,
		DependencyIndexes: file_TDCmicroserviceAPI_proto_depIdxs,
		MessageInfos:      file_TDCmicroserviceAPI_proto_msgTypes,
	}.Build()
	File_TDCmicroserviceAPI_proto = out.File
	file_TDCmicroserviceAPI_proto_rawDesc = nil
	file_TDCmicroserviceAPI_proto_goTypes = nil
	file_TDCmicroserviceAPI_proto_depIdxs = nil
}
