global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: ['application:8080', 'application', 'kube-proxy:10249']
