apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: application
    tier: tdc
spec:
  type: LoadBalancer
  selector:
    app: spring-sample-tdc
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
